services:
  backend:
    image: golang:1.22
    container_name: backend
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD:?Please provide a password}@postgres:5432/${POSTGRES_DB:-barbedworkdb}?sslmode=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
