services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL=postgres://postgres:${POSTGRES_PASSWORD:?Please provide a password}@postgres:5432/${POSTGRES_DB:-barbedworkdb}?sslmode=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ADMIN_PANEL_PASSWORD=${ADMIN_PANEL_PASSWORD:?Please provide an admin panel password}
      - DEV=${DEV:-false}
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Please provide a password}
      POSTGRES_DB: ${POSTGRES_DB:-barbedworkdb}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: